/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * Development documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetV1Stats200Response,
} from '../models/index';
import {
    GetV1Stats200ResponseFromJSON,
    GetV1Stats200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class APIApi extends runtime.BaseAPI {

    /**
     * health check for API
     */
    async getIndexRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * health check for API
     */
    async getIndex(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getIndexRaw(initOverrides);
    }

    /**
     * Get stats from the API
     */
    async getV1StatsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetV1Stats200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/stats`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetV1Stats200ResponseFromJSON(jsonValue));
    }

    /**
     * Get stats from the API
     */
    async getV1Stats(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetV1Stats200Response> {
        const response = await this.getV1StatsRaw(initOverrides);
        return await response.value();
    }

}
