/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HttpError,
  V1IceServers200Response,
  V1IceServersRequest,
} from '../models/index';
import {
    HttpErrorFromJSON,
    HttpErrorToJSON,
    V1IceServers200ResponseFromJSON,
    V1IceServers200ResponseToJSON,
    V1IceServersRequestFromJSON,
    V1IceServersRequestToJSON,
} from '../models/index';

export interface V1IceServersOperationRequest {
    v1IceServersRequest: V1IceServersRequest;
    authorization?: string;
}

/**
 * 
 */
export class ICEApi extends runtime.BaseAPI {

    /**
     */
    async v1IceServersRaw(requestParameters: V1IceServersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1IceServers200Response>> {
        if (requestParameters['v1IceServersRequest'] == null) {
            throw new runtime.RequiredError(
                'v1IceServersRequest',
                'Required parameter "v1IceServersRequest" was null or undefined when calling v1IceServers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/ice-servers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: V1IceServersRequestToJSON(requestParameters['v1IceServersRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1IceServers200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async v1IceServers(requestParameters: V1IceServersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1IceServers200Response> {
        const response = await this.v1IceServersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
