/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HttpError,
  V1DeviceConnect200Response,
  V1DeviceConnectRequest,
} from '../models/index';
import {
    HttpErrorFromJSON,
    HttpErrorToJSON,
    V1DeviceConnect200ResponseFromJSON,
    V1DeviceConnect200ResponseToJSON,
    V1DeviceConnectRequestFromJSON,
    V1DeviceConnectRequestToJSON,
} from '../models/index';

export interface V1DeviceConnectOperationRequest {
    authorization: string;
    v1DeviceConnectRequest: V1DeviceConnectRequest;
}

/**
 * 
 */
export class DeviceApi extends runtime.BaseAPI {

    /**
     */
    async v1DeviceConnectRaw(requestParameters: V1DeviceConnectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1DeviceConnect200Response>> {
        if (requestParameters['authorization'] == null) {
            throw new runtime.RequiredError(
                'authorization',
                'Required parameter "authorization" was null or undefined when calling v1DeviceConnect().'
            );
        }

        if (requestParameters['v1DeviceConnectRequest'] == null) {
            throw new runtime.RequiredError(
                'v1DeviceConnectRequest',
                'Required parameter "v1DeviceConnectRequest" was null or undefined when calling v1DeviceConnect().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/device/connect`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: V1DeviceConnectRequestToJSON(requestParameters['v1DeviceConnectRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1DeviceConnect200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async v1DeviceConnect(requestParameters: V1DeviceConnectOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1DeviceConnect200Response> {
        const response = await this.v1DeviceConnectRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
