/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * Development documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HttpError,
  PostV1IceServers200Response,
  PostV1IceServersRequest,
} from '../models/index';
import {
    HttpErrorFromJSON,
    HttpErrorToJSON,
    PostV1IceServers200ResponseFromJSON,
    PostV1IceServers200ResponseToJSON,
    PostV1IceServersRequestFromJSON,
    PostV1IceServersRequestToJSON,
} from '../models/index';

export interface PostV1IceServersOperationRequest {
    postV1IceServersRequest: PostV1IceServersRequest;
    authorization?: string;
}

/**
 * 
 */
export class ICEApi extends runtime.BaseAPI {

    /**
     * Get ICE server configuration
     */
    async postV1IceServersRaw(requestParameters: PostV1IceServersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostV1IceServers200Response>> {
        if (requestParameters['postV1IceServersRequest'] == null) {
            throw new runtime.RequiredError(
                'postV1IceServersRequest',
                'Required parameter "postV1IceServersRequest" was null or undefined when calling postV1IceServers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/v1/ice-servers`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostV1IceServersRequestToJSON(requestParameters['postV1IceServersRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostV1IceServers200ResponseFromJSON(jsonValue));
    }

    /**
     * Get ICE server configuration
     */
    async postV1IceServers(requestParameters: PostV1IceServersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostV1IceServers200Response> {
        const response = await this.postV1IceServersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
