/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Http Error
 * @export
 * @interface HttpError
 */
export interface HttpError {
    /**
     * 
     * @type {string}
     * @memberof HttpError
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof HttpError
     */
    code?: string;
}

/**
 * Check if a given object implements the HttpError interface.
 */
export function instanceOfHttpError(value: object): value is HttpError {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function HttpErrorFromJSON(json: any): HttpError {
    return HttpErrorFromJSONTyped(json, false);
}

export function HttpErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpError {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function HttpErrorToJSON(json: any): HttpError {
    return HttpErrorToJSONTyped(json, false);
}

export function HttpErrorToJSONTyped(value?: HttpError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'code': value['code'],
    };
}

