/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * Development documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostV1ClientConnect200Response
 */
export interface PostV1ClientConnect200Response {
    /**
     * 
     * @type {string}
     * @memberof PostV1ClientConnect200Response
     */
    signalingUrl: string;
    /**
     * 
     * @type {boolean}
     * @memberof PostV1ClientConnect200Response
     */
    deviceOnline?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PostV1ClientConnect200Response
     */
    channelId: string;
}

/**
 * Check if a given object implements the PostV1ClientConnect200Response interface.
 */
export function instanceOfPostV1ClientConnect200Response(value: object): value is PostV1ClientConnect200Response {
    if (!('signalingUrl' in value) || value['signalingUrl'] === undefined) return false;
    if (!('channelId' in value) || value['channelId'] === undefined) return false;
    return true;
}

export function PostV1ClientConnect200ResponseFromJSON(json: any): PostV1ClientConnect200Response {
    return PostV1ClientConnect200ResponseFromJSONTyped(json, false);
}

export function PostV1ClientConnect200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostV1ClientConnect200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'signalingUrl': json['signalingUrl'],
        'deviceOnline': json['deviceOnline'] == null ? undefined : json['deviceOnline'],
        'channelId': json['channelId'],
    };
}

  export function PostV1ClientConnect200ResponseToJSON(json: any): PostV1ClientConnect200Response {
      return PostV1ClientConnect200ResponseToJSONTyped(json, false);
  }

  export function PostV1ClientConnect200ResponseToJSONTyped(value?: PostV1ClientConnect200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signalingUrl': value['signalingUrl'],
        'deviceOnline': value['deviceOnline'],
        'channelId': value['channelId'],
    };
}

