/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * Development documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Expected a device ID
 * @export
 * @interface PostV1IceServersRequest
 */
export interface PostV1IceServersRequest {
    /**
     * 
     * @type {string}
     * @memberof PostV1IceServersRequest
     */
    deviceId: string;
    /**
     * 
     * @type {string}
     * @memberof PostV1IceServersRequest
     */
    productId: string;
}

/**
 * Check if a given object implements the PostV1IceServersRequest interface.
 */
export function instanceOfPostV1IceServersRequest(value: object): value is PostV1IceServersRequest {
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    return true;
}

export function PostV1IceServersRequestFromJSON(json: any): PostV1IceServersRequest {
    return PostV1IceServersRequestFromJSONTyped(json, false);
}

export function PostV1IceServersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostV1IceServersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['deviceId'],
        'productId': json['productId'],
    };
}

  export function PostV1IceServersRequestToJSON(json: any): PostV1IceServersRequest {
      return PostV1IceServersRequestToJSONTyped(json, false);
  }

  export function PostV1IceServersRequestToJSONTyped(value?: PostV1IceServersRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceId': value['deviceId'],
        'productId': value['productId'],
    };
}

