/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * Development documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Expected a device ID and a product ID
 * @export
 * @interface PostV1ClientConnectRequest
 */
export interface PostV1ClientConnectRequest {
    /**
     * 
     * @type {string}
     * @memberof PostV1ClientConnectRequest
     */
    deviceId: string;
    /**
     * 
     * @type {string}
     * @memberof PostV1ClientConnectRequest
     */
    productId: string;
}

/**
 * Check if a given object implements the PostV1ClientConnectRequest interface.
 */
export function instanceOfPostV1ClientConnectRequest(value: object): value is PostV1ClientConnectRequest {
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    return true;
}

export function PostV1ClientConnectRequestFromJSON(json: any): PostV1ClientConnectRequest {
    return PostV1ClientConnectRequestFromJSONTyped(json, false);
}

export function PostV1ClientConnectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostV1ClientConnectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['deviceId'],
        'productId': json['productId'],
    };
}

  export function PostV1ClientConnectRequestToJSON(json: any): PostV1ClientConnectRequest {
      return PostV1ClientConnectRequestToJSONTyped(json, false);
  }

  export function PostV1ClientConnectRequestToJSONTyped(value?: PostV1ClientConnectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceId': value['deviceId'],
        'productId': value['productId'],
    };
}

