/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Expects a device ID and a product ID
 * @export
 * @interface V1ClientConnectRequest
 */
export interface V1ClientConnectRequest {
    /**
     * Nabto Device ID
     * @type {string}
     * @memberof V1ClientConnectRequest
     */
    deviceId: string;
    /**
     * Nabto Product ID
     * @type {string}
     * @memberof V1ClientConnectRequest
     */
    productId: string;
}

/**
 * Check if a given object implements the V1ClientConnectRequest interface.
 */
export function instanceOfV1ClientConnectRequest(value: object): value is V1ClientConnectRequest {
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    return true;
}

export function V1ClientConnectRequestFromJSON(json: any): V1ClientConnectRequest {
    return V1ClientConnectRequestFromJSONTyped(json, false);
}

export function V1ClientConnectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ClientConnectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['deviceId'],
        'productId': json['productId'],
    };
}

export function V1ClientConnectRequestToJSON(json: any): V1ClientConnectRequest {
    return V1ClientConnectRequestToJSONTyped(json, false);
}

export function V1ClientConnectRequestToJSONTyped(value?: V1ClientConnectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceId': value['deviceId'],
        'productId': value['productId'],
    };
}

