/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * Development documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetV1Stats200Response
 */
export interface GetV1Stats200Response {
    /**
     * 
     * @type {number}
     * @memberof GetV1Stats200Response
     */
    connectedPeers?: number;
}

/**
 * Check if a given object implements the GetV1Stats200Response interface.
 */
export function instanceOfGetV1Stats200Response(value: object): value is GetV1Stats200Response {
    return true;
}

export function GetV1Stats200ResponseFromJSON(json: any): GetV1Stats200Response {
    return GetV1Stats200ResponseFromJSONTyped(json, false);
}

export function GetV1Stats200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetV1Stats200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'connectedPeers': json['connectedPeers'] == null ? undefined : json['connectedPeers'],
    };
}

  export function GetV1Stats200ResponseToJSON(json: any): GetV1Stats200Response {
      return GetV1Stats200ResponseToJSONTyped(json, false);
  }

  export function GetV1Stats200ResponseToJSONTyped(value?: GetV1Stats200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connectedPeers': value['connectedPeers'],
    };
}

