/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * Development documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostV1IceServers200ResponseIceServersInner
 */
export interface PostV1IceServers200ResponseIceServersInner {
    /**
     * 
     * @type {Array<string>}
     * @memberof PostV1IceServers200ResponseIceServersInner
     */
    urls: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PostV1IceServers200ResponseIceServersInner
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof PostV1IceServers200ResponseIceServersInner
     */
    credential?: string;
}

/**
 * Check if a given object implements the PostV1IceServers200ResponseIceServersInner interface.
 */
export function instanceOfPostV1IceServers200ResponseIceServersInner(value: object): value is PostV1IceServers200ResponseIceServersInner {
    if (!('urls' in value) || value['urls'] === undefined) return false;
    return true;
}

export function PostV1IceServers200ResponseIceServersInnerFromJSON(json: any): PostV1IceServers200ResponseIceServersInner {
    return PostV1IceServers200ResponseIceServersInnerFromJSONTyped(json, false);
}

export function PostV1IceServers200ResponseIceServersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostV1IceServers200ResponseIceServersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'urls': json['urls'],
        'username': json['username'] == null ? undefined : json['username'],
        'credential': json['credential'] == null ? undefined : json['credential'],
    };
}

  export function PostV1IceServers200ResponseIceServersInnerToJSON(json: any): PostV1IceServers200ResponseIceServersInner {
      return PostV1IceServers200ResponseIceServersInnerToJSONTyped(json, false);
  }

  export function PostV1IceServers200ResponseIceServersInnerToJSONTyped(value?: PostV1IceServers200ResponseIceServersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'urls': value['urls'],
        'username': value['username'],
        'credential': value['credential'],
    };
}

