/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * Development documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostV1DeviceConnect200Response
 */
export interface PostV1DeviceConnect200Response {
    /**
     * 
     * @type {string}
     * @memberof PostV1DeviceConnect200Response
     */
    signalingUrl: string;
}

/**
 * Check if a given object implements the PostV1DeviceConnect200Response interface.
 */
export function instanceOfPostV1DeviceConnect200Response(value: object): value is PostV1DeviceConnect200Response {
    if (!('signalingUrl' in value) || value['signalingUrl'] === undefined) return false;
    return true;
}

export function PostV1DeviceConnect200ResponseFromJSON(json: any): PostV1DeviceConnect200Response {
    return PostV1DeviceConnect200ResponseFromJSONTyped(json, false);
}

export function PostV1DeviceConnect200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostV1DeviceConnect200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'signalingUrl': json['signalingUrl'],
    };
}

  export function PostV1DeviceConnect200ResponseToJSON(json: any): PostV1DeviceConnect200Response {
      return PostV1DeviceConnect200ResponseToJSONTyped(json, false);
  }

  export function PostV1DeviceConnect200ResponseToJSONTyped(value?: PostV1DeviceConnect200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signalingUrl': value['signalingUrl'],
    };
}

