/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * OK
 * @export
 * @interface V1ClientConnect200Response
 */
export interface V1ClientConnect200Response {
    /**
     * 
     * @type {string}
     * @memberof V1ClientConnect200Response
     */
    signalingUrl: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1ClientConnect200Response
     */
    deviceOnline: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1ClientConnect200Response
     */
    channelId: string;
}

/**
 * Check if a given object implements the V1ClientConnect200Response interface.
 */
export function instanceOfV1ClientConnect200Response(value: object): value is V1ClientConnect200Response {
    if (!('signalingUrl' in value) || value['signalingUrl'] === undefined) return false;
    if (!('deviceOnline' in value) || value['deviceOnline'] === undefined) return false;
    if (!('channelId' in value) || value['channelId'] === undefined) return false;
    return true;
}

export function V1ClientConnect200ResponseFromJSON(json: any): V1ClientConnect200Response {
    return V1ClientConnect200ResponseFromJSONTyped(json, false);
}

export function V1ClientConnect200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ClientConnect200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'signalingUrl': json['signalingUrl'],
        'deviceOnline': json['deviceOnline'],
        'channelId': json['channelId'],
    };
}

export function V1ClientConnect200ResponseToJSON(json: any): V1ClientConnect200Response {
    return V1ClientConnect200ResponseToJSONTyped(json, false);
}

export function V1ClientConnect200ResponseToJSONTyped(value?: V1ClientConnect200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signalingUrl': value['signalingUrl'],
        'deviceOnline': value['deviceOnline'],
        'channelId': value['channelId'],
    };
}

