/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Expects a device ID and a product ID
 * @export
 * @interface V1ClientConnectPostRequest
 */
export interface V1ClientConnectPostRequest {
    /**
     * Nabto Device ID
     * @type {string}
     * @memberof V1ClientConnectPostRequest
     */
    deviceId: string;
    /**
     * Nabto Product ID
     * @type {string}
     * @memberof V1ClientConnectPostRequest
     */
    productId: string;
}

/**
 * Check if a given object implements the V1ClientConnectPostRequest interface.
 */
export function instanceOfV1ClientConnectPostRequest(value: object): value is V1ClientConnectPostRequest {
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    return true;
}

export function V1ClientConnectPostRequestFromJSON(json: any): V1ClientConnectPostRequest {
    return V1ClientConnectPostRequestFromJSONTyped(json, false);
}

export function V1ClientConnectPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ClientConnectPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['deviceId'],
        'productId': json['productId'],
    };
}

export function V1ClientConnectPostRequestToJSON(json: any): V1ClientConnectPostRequest {
    return V1ClientConnectPostRequestToJSONTyped(json, false);
}

export function V1ClientConnectPostRequestToJSONTyped(value?: V1ClientConnectPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceId': value['deviceId'],
        'productId': value['productId'],
    };
}

