/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * OK
 * @export
 * @interface V1DeviceConnectPost200Response
 */
export interface V1DeviceConnectPost200Response {
    /**
     * 
     * @type {string}
     * @memberof V1DeviceConnectPost200Response
     */
    signalingUrl: string;
}

/**
 * Check if a given object implements the V1DeviceConnectPost200Response interface.
 */
export function instanceOfV1DeviceConnectPost200Response(value: object): value is V1DeviceConnectPost200Response {
    if (!('signalingUrl' in value) || value['signalingUrl'] === undefined) return false;
    return true;
}

export function V1DeviceConnectPost200ResponseFromJSON(json: any): V1DeviceConnectPost200Response {
    return V1DeviceConnectPost200ResponseFromJSONTyped(json, false);
}

export function V1DeviceConnectPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DeviceConnectPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'signalingUrl': json['signalingUrl'],
    };
}

export function V1DeviceConnectPost200ResponseToJSON(json: any): V1DeviceConnectPost200Response {
    return V1DeviceConnectPost200ResponseToJSONTyped(json, false);
}

export function V1DeviceConnectPost200ResponseToJSONTyped(value?: V1DeviceConnectPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signalingUrl': value['signalingUrl'],
    };
}

