/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Expected a device ID
 * @export
 * @interface V1DeviceConnectPostRequest
 */
export interface V1DeviceConnectPostRequest {
    /**
     * 
     * @type {string}
     * @memberof V1DeviceConnectPostRequest
     */
    deviceId: string;
    /**
     * 
     * @type {string}
     * @memberof V1DeviceConnectPostRequest
     */
    productId: string;
}

/**
 * Check if a given object implements the V1DeviceConnectPostRequest interface.
 */
export function instanceOfV1DeviceConnectPostRequest(value: object): value is V1DeviceConnectPostRequest {
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    return true;
}

export function V1DeviceConnectPostRequestFromJSON(json: any): V1DeviceConnectPostRequest {
    return V1DeviceConnectPostRequestFromJSONTyped(json, false);
}

export function V1DeviceConnectPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DeviceConnectPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['deviceId'],
        'productId': json['productId'],
    };
}

export function V1DeviceConnectPostRequestToJSON(json: any): V1DeviceConnectPostRequest {
    return V1DeviceConnectPostRequestToJSONTyped(json, false);
}

export function V1DeviceConnectPostRequestToJSONTyped(value?: V1DeviceConnectPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceId': value['deviceId'],
        'productId': value['productId'],
    };
}

