/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1IceServersPost200ResponseIceServersInner } from './V1IceServersPost200ResponseIceServersInner';
import {
    V1IceServersPost200ResponseIceServersInnerFromJSON,
    V1IceServersPost200ResponseIceServersInnerFromJSONTyped,
    V1IceServersPost200ResponseIceServersInnerToJSON,
    V1IceServersPost200ResponseIceServersInnerToJSONTyped,
} from './V1IceServersPost200ResponseIceServersInner';

/**
 * OK
 * @export
 * @interface V1IceServersPost200Response
 */
export interface V1IceServersPost200Response {
    /**
     * 
     * @type {Array<V1IceServersPost200ResponseIceServersInner>}
     * @memberof V1IceServersPost200Response
     */
    iceServers: Array<V1IceServersPost200ResponseIceServersInner>;
}

/**
 * Check if a given object implements the V1IceServersPost200Response interface.
 */
export function instanceOfV1IceServersPost200Response(value: object): value is V1IceServersPost200Response {
    if (!('iceServers' in value) || value['iceServers'] === undefined) return false;
    return true;
}

export function V1IceServersPost200ResponseFromJSON(json: any): V1IceServersPost200Response {
    return V1IceServersPost200ResponseFromJSONTyped(json, false);
}

export function V1IceServersPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1IceServersPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'iceServers': ((json['iceServers'] as Array<any>).map(V1IceServersPost200ResponseIceServersInnerFromJSON)),
    };
}

export function V1IceServersPost200ResponseToJSON(json: any): V1IceServersPost200Response {
    return V1IceServersPost200ResponseToJSONTyped(json, false);
}

export function V1IceServersPost200ResponseToJSONTyped(value?: V1IceServersPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iceServers': ((value['iceServers'] as Array<any>).map(V1IceServersPost200ResponseIceServersInnerToJSON)),
    };
}

