/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1IceServersPost200ResponseIceServersInner
 */
export interface V1IceServersPost200ResponseIceServersInner {
    /**
     * 
     * @type {Array<string>}
     * @memberof V1IceServersPost200ResponseIceServersInner
     */
    urls: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof V1IceServersPost200ResponseIceServersInner
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof V1IceServersPost200ResponseIceServersInner
     */
    credential?: string;
}

/**
 * Check if a given object implements the V1IceServersPost200ResponseIceServersInner interface.
 */
export function instanceOfV1IceServersPost200ResponseIceServersInner(value: object): value is V1IceServersPost200ResponseIceServersInner {
    if (!('urls' in value) || value['urls'] === undefined) return false;
    return true;
}

export function V1IceServersPost200ResponseIceServersInnerFromJSON(json: any): V1IceServersPost200ResponseIceServersInner {
    return V1IceServersPost200ResponseIceServersInnerFromJSONTyped(json, false);
}

export function V1IceServersPost200ResponseIceServersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1IceServersPost200ResponseIceServersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'urls': json['urls'],
        'username': json['username'] == null ? undefined : json['username'],
        'credential': json['credential'] == null ? undefined : json['credential'],
    };
}

export function V1IceServersPost200ResponseIceServersInnerToJSON(json: any): V1IceServersPost200ResponseIceServersInner {
    return V1IceServersPost200ResponseIceServersInnerToJSONTyped(json, false);
}

export function V1IceServersPost200ResponseIceServersInnerToJSONTyped(value?: V1IceServersPost200ResponseIceServersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'urls': value['urls'],
        'username': value['username'],
        'credential': value['credential'],
    };
}

