/* tslint:disable */
/* eslint-disable */
/**
 * Nabto WebRTC Signaling
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1IceServers200ResponseIceServersInner } from './V1IceServers200ResponseIceServersInner';
import {
    V1IceServers200ResponseIceServersInnerFromJSON,
    V1IceServers200ResponseIceServersInnerFromJSONTyped,
    V1IceServers200ResponseIceServersInnerToJSON,
    V1IceServers200ResponseIceServersInnerToJSONTyped,
} from './V1IceServers200ResponseIceServersInner';

/**
 * OK
 * @export
 * @interface V1IceServers200Response
 */
export interface V1IceServers200Response {
    /**
     * 
     * @type {Array<V1IceServers200ResponseIceServersInner>}
     * @memberof V1IceServers200Response
     */
    iceServers: Array<V1IceServers200ResponseIceServersInner>;
}

/**
 * Check if a given object implements the V1IceServers200Response interface.
 */
export function instanceOfV1IceServers200Response(value: object): value is V1IceServers200Response {
    if (!('iceServers' in value) || value['iceServers'] === undefined) return false;
    return true;
}

export function V1IceServers200ResponseFromJSON(json: any): V1IceServers200Response {
    return V1IceServers200ResponseFromJSONTyped(json, false);
}

export function V1IceServers200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1IceServers200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'iceServers': ((json['iceServers'] as Array<any>).map(V1IceServers200ResponseIceServersInnerFromJSON)),
    };
}

export function V1IceServers200ResponseToJSON(json: any): V1IceServers200Response {
    return V1IceServers200ResponseToJSONTyped(json, false);
}

export function V1IceServers200ResponseToJSONTyped(value?: V1IceServers200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iceServers': ((value['iceServers'] as Array<any>).map(V1IceServers200ResponseIceServersInnerToJSON)),
    };
}

