name: Run Integration tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        project: [ "@nabto/webrtc-signaling-client", "@nabto/webrtc-signaling-device"]
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - uses: pnpm/action-setup@v4
       name: Install pnpm
       with:
        run_install: false

     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
        node-version: 22
        cache: 'pnpm'

     - uses: oven-sh/setup-bun@v2

     - name: Install integration test server
       run: bun install
       working-directory: integration_test_server

     - name: Start integration test server
       run: bun dev &
       working-directory: integration_test_server

     - name: Install sdk
       run: |
        pnpm --filter ${{ matrix.project }} install
        pnpm --filter ${{ matrix.project }} build

     - name: run lint
       run: pnpm --filter ${{ matrix.project }} lint

     - name: Run tests
       run: pnpm --filter ${{matrix.project }} test:i
